package main

import (
	"log"
	"qotera-backend/internal/domain"
	"qotera-backend/internal/handler"
	"qotera-backend/internal/middleware"
	"qotera-backend/internal/repository"
	"qotera-backend/internal/service"
	"qotera-backend/pkg/config"
	"qotera-backend/pkg/database"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"github.com/gofiber/swagger" // swagger middleware

	_ "qotera-backend/docs" // docs are generated by Swag CLI
)

// @title Qotera API
// @version 1.0
// @description Qotera Expense Intelligence Platform API
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.email support@qotera.com

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:3000
// @BasePath /
func main() {
	// Load config
	cfg := config.LoadConfig()

	// Connect to database
	db, err := database.ConnectDB(cfg)
	if err != nil {
		log.Fatalf("Failed to connect to database: %v", err)
	}

	// Auto Migrate
	err = db.AutoMigrate(
		&domain.User{},
		&domain.Transaction{},
		&domain.Account{},
		&domain.Budget{},
	)
	if err != nil {
		log.Fatalf("Failed to run auto migrations: %v", err)
	}

	// Initialize Repositories
	userRepo := repository.NewUserRepository(db)
	transactionRepo := repository.NewTransactionRepository(db)
	budgetRepo := repository.NewBudgetRepository(db)

	// Initialize Services
	userService := service.NewUserService(userRepo)
	authService := service.NewAuthService(userRepo)
	transactionService := service.NewTransactionService(transactionRepo)
	budgetService := service.NewBudgetService(budgetRepo, transactionRepo)

	// Initialize Handlers
	authHandler := handler.NewAuthHandler(authService, userService)
	transactionHandler := handler.NewTransactionHandler(transactionService)
	budgetHandler := handler.NewBudgetHandler(budgetService)

	// Initialize Fiber app
	app := fiber.New()

	// Logger middleware
	app.Use(logger.New())

	// Swagger Route
	app.Get("/swagger/*", swagger.HandlerDefault)

	// Generic route for health check
	// @Summary Health Check
	// @Description Check if the server is running
	// @Tags Health
	// @Produce plain
	// @Success 200 {string} string "Qotera Backend is Running!"
	// @Router / [get]
	app.Get("/", func(c *fiber.Ctx) error {
		return c.SendString("Qotera Backend is Running!")
	})

	// Auth Routes
	auth := app.Group("/auth")
	auth.Post("/login", authHandler.Login)
	auth.Post("/verify", authHandler.VerifyOTP)
	auth.Get("/me", middleware.AuthMiddleware(), authHandler.Me)

	// Transaction Sync and Aggregation Routes
	transactions := app.Group("/transactions")
	transactions.Use(middleware.AuthMiddleware())
	transactions.Post("/sync", transactionHandler.SyncTransactions)
	transactions.Get("/", transactionHandler.GetTransactions)
	transactions.Get("/summary", transactionHandler.GetSummary)

	// Budget Routes
	budgets := app.Group("/budgets")
	budgets.Use(middleware.AuthMiddleware())
	budgets.Post("/", budgetHandler.SetBudget)
	budgets.Get("/", budgetHandler.GetBudgets)

	// Start server
	log.Fatal(app.Listen(":" + cfg.ServerPort))
}
